-- AlterTable
ALTER TABLE "Squad" ADD COLUMN     "dailyScrumMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "planningHours" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "refinementHours" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "retrospectiveMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "reviewDemoMinutes" INTEGER NOT NULL DEFAULT 30;
