openapi: 3.0.3
info:
  title: Member Hours API
  version: 1.0.0
  description: API for managing member hours in capacity planning

servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://www.sprintcap.info/api
    description: Production server

paths:
  /member-hours:
    get:
      summary: Get member hours for a sprint
      parameters:
        - name: sprintId
          in: query
          required: true
          schema:
            type: string
          description: The sprint ID to get hours for
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MemberHours'
        '400':
          description: Invalid sprint ID
        '401':
          description: Unauthorized
        '500':
          description: Server error
      security:
        - bearerAuth: []

    put:
      summary: Update member hours
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberHoursUpdate'
      responses:
        '200':
          description: Hours updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberHours'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized
        '404':
          description: Member or sprint not found
        '500':
          description: Server error
      security:
        - bearerAuth: []

components:
  schemas:
    MemberHours:
      type: object
      properties:
        id:
          type: string
        memberId:
          type: string
        sprintId:
          type: string
        memberName:
          type: string
          description: Display name for UI
        supportIncidents:
          type: number
          format: float
          minimum: 0
          default: 0
        prReview:
          type: number
          format: float
          minimum: 0
          default: 0
        others:
          type: number
          format: float
          minimum: 0
          default: 0
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - memberId
        - sprintId
        - supportIncidents
        - prReview
        - others

    MemberHoursUpdate:
      type: object
      properties:
        memberId:
          type: string
        sprintId:
          type: string
        supportIncidents:
          type: number
          format: float
          minimum: 0
        prReview:
          type: number
          format: float
          minimum: 0
        others:
          type: number
          format: float
          minimum: 0
      required:
        - memberId
        - sprintId

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT