import "./globals.css"

export const metadata = {
  title: 'Sprint Capacity',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.svg',
  },
}

import Providers from "../components/providers"
import Footer from "../components/Footer"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Providers>{children}</Providers>
  <Footer />
      </body>
    </html>
  )
}
