name: CI

on:
  push:
    branches: [ main, master, '003-i-want-this' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Validate env files for empty critical keys
        run: npm run validate:env

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Run build (optional, may require secrets)
        run: npm run build
