name: CI

on:
  push:
    branches: [ main, master, '003-i-want-this' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Validate env files for empty critical keys
        run: npm run validate:env

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Run unit & contract tests (Vitest)
        run: npm test --silent

  e2e:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Start dev server
        run: npm run dev &
      - name: Wait for dev server
        run: |
          n=0
          until curl --silent --fail http://localhost:3000/ || [ $n -ge 15 ]; do
            n=$((n+1))
            sleep 1
          done
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --reporter=github || true
      - name: Generate Playwright HTML report
        if: always()
        run: npx playwright show-report || true
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results
