name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate --schema=prisma/schema.prisma || true
      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start dev server
        run: |
          npm run build
          npm run start &
        env:
          PORT: 3000
      - name: Run Playwright tests
        run: npx playwright test --reporter=list
        continue-on-error: true
      - name: Upload Playwright Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-report
